// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vliuwkgsezxfwdgdlkuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsaXV3a2dzZXp4ZndkZ2Rsa3V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzM3OTQsImV4cCI6MjA2NDcwOTc5NH0.HwIbDct02m_jLSVykLtRzYhRTWNeGjkIyCpO-DO62gU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);